### ISSUE TITLE
Starting the webserver fails: The error code 12288 is unknown in ERR_CODES

### ISSUE THREAD

**Issue by pklaus** [pklaus/MaxiGauge#1]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/coltrims/MaxiGauge/PfeifferVacuum.py", line 118, in continuous_pressure_updates
    self.cached_pressures = self.pressures()
  File "/home/coltrims/MaxiGauge/PfeifferVacuum.py", line 63, in pressures
    return [self.pressure(i+1) for i in range(6)]
  File "/home/coltrims/MaxiGauge/PfeifferVacuum.py", line 67, in pressure
    reading = self.send('PR%d' % sensor, 1)  ## reading will have the form x,x.xxxEsx <CR><LF> (see p.88)
  File "/home/coltrims/MaxiGauge/PfeifferVacuum.py", line 166, in send
    self.getACQorNAK()
  File "/home/coltrims/MaxiGauge/PfeifferVacuum.py", line 201, in getACQorNAK
    errmsg = { 'System Error': ERR_CODES[0][int(error[0])] , 'Gauge Error': ERR_CODES[1][int(error[1])] }
KeyError: 12288
```

**Comment by pklaus** [comment]
OK, it seems like there can be multiple errors at once:

``` python
contained = lambda flag: (12288 & flag) == flag
for i in range(0,12288):
    if contained(i): print i
```

prints:

```
0
4096
8192
```

So the errors defined in [PfeifferVacuum.py#L295](https://github.com/pklaus/MaxiGauge/blob/94fc623eb8899ec22cffb8e4c05eb6e4d1208ef4/PfeifferVacuum.py#L295) have to be parsed differently.
